---
- name: build mail.talideon.com
  hosts: manann.talideon.com
  remote_user: keith
  become: true
  gather_facts: false

  vars:
    domain_name: mail.talideon.com
    webserver_config_root: /usr/local/etc/nginx
    tls_root: /usr/local/etc/ssl/acme
    acme_client_root: /usr/local/etc/acme
    acme_challenge_dir: /usr/local/www/acme

  tasks:
    - name: populate domains.txt
      lineinfile:
        dest: "{{ acme_client_root }}/domains.txt"
        create: true
        line: "{{ domain_name }}"
      notify:
        - generate missing certificates
        - reload nginx

    - name: copy up custom vhost config
      template:
        src: "vhost.j2"
        dest: "{{ webserver_config_root }}/vhosts/{{ domain_name }}"
      notify:
        - reload nginx

  handlers:
    - name: generate missing certificates
      command:
        argv:
          - "{{ acme_client_root }}/acme-domain-renew"
          - "-c"
          - "{{ acme_client_root }}"
          - "-w"
          - "{{ acme_challenge_dir }}"
          - "-t"
          - "{{ tls_root }}"

    - name: reload nginx
      service:
        name: nginx
        state: reloaded
