---
- name: build {{ domain_name }}
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - stat:
        path: "sites/{{ domain_name }}/mkdocs.yml"
      register: stat

    - assert:
        that: stat.stat.exists
        msg: "{{ stat.stat.path }} does not exist."

    - tempfile:
        state: directory
      register: local_tmp

    # To persist across plays.
    - set_fact:
        tmp: "{{ local_tmp.path }}"

    - shell: mkdocs build --strict --site-dir {{ local_tmp.path }}
      args:
        chdir: "sites/{{ domain_name }}"

- name: deploy {{ domain_name }}
  hosts: all
  remote_user: keith
  become: true
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/local/bin/python

    # domain_name comes in from the invocation.
    vhosts_root: /usr/local/www
    webserver_config_root: /usr/local/etc/nginx
    acme_client_root: /usr/local/etc/acme
    tls_root: /usr/local/etc/ssl/acme
    logs_root: /var/log/www
    tmp: "{{ hostvars.localhost.tmp }}"

  tasks:
    - name: ensure target directories exist
      file:
        dest: '{{ item }}'
        state: directory
        owner: www
        group: wheel
        mode: 0755
      with_items:
        - '{{ vhosts_root }}/{{ domain_name }}/web'
        - '{{ webserver_config_root }}/vhosts'
        - '{{ logs_root }}'

    - name: populate domains.txt
      lineinfile:
        dest: "{{ acme_client_root }}/domains.txt"
        create: true
        line: "{{ domain_name }}"

    - name: check if the cert already exists
      stat:
        path: "{{ tls_root }}/{{ domain_name }}/fullchain.pem"
      register: chain

    - name: generate missing certificates
      command: "{{ acme_client_root }}/acme-client.sh"
      when: not chain.stat.exists

    - name: copy up vhost config
      template:
        src: vhost.conf.j2
        dest: '{{ webserver_config_root }}/vhosts/{{ domain_name }}'
      notify:
        - reload nginx

    - name: copy up site
      synchronize:
        src: "{{ tmp }}/"
        dest: "{{ vhosts_root }}/{{ domain_name }}/web"
        group: false
        owner: false
        perms: false
        delete: true

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
      ignore_errors: true
