---
site_name: talideon.com
copyright: Keith Gaughan, 2001-2019

theme:
  name: null
  custom_dir: ../../themes/minimal

markdown_extensions:
  - smarty
  - sane_lists

plugins: []

nav:
  - Home: index.md
