site_name: Mirrored content hosted on mirrors.talideon.com

theme:
  name: null
  custom_dir: ../../themes/sheets

markdown_extensions:
  - attr_list
  - def_list
  - sane_lists
  - smarty

plugins: []

use_directory_urls: false

nav:
  - Home: index.md
  - Conlanging:
      - Kalaba-X: articles/kalabax.md
      - Breathanach: articles/morven/breathanach.md
  - Esolangs:
      - Q-BAL: articles/qbal/index.md
      - Malbolge: articles/malbolge/spec.md
      - Dis: articles/malbolge/dis.md
  - Other:
      - XML-RPC Multicall: articles/multicall.md
      - Caring for your introvert: articles/rauch.md
