site_name: talideon.com
copyright: Keith Gaughan, 2001-2018

theme:
  name: null
  custom_dir: ../../themes/simple

pages:
  - Home: index.md
  - Articles:
      - Web development notes: webdev-notes.md
      - Getting Ubuntu running on a Lenovo Miix 310: ubuntu-lenovo-miix-310.md
  - Elsewhere: elsewhere.md
