---
- name: build talideon.com
  hosts: lir.talideon.com
  remote_user: keith
  become: true
  gather_facts: false

  vars:
    domain_name: talideon.com
    vhosts_root: /usr/local/www
    webserver_config_root: /usr/local/etc/nginx
    logs_root: /var/log/www
    tls_root: /usr/local/etc/ssl/acme
    acme_client_root: /usr/local/etc/acme
    acme_challenge_dir: /usr/local/www/acme
    db_path: /var/db/komorebi/db.sqlite

  tasks:
    - name: create local build directory
      local_action:
        module: tempfile
        state: directory
      become: false
      register: build_dir

    - name: build site
      local_action: command mkdocs build --strict --site-dir {{ build_dir.path }}
      become: false

    - name: install packages
      pkgng:
        name:
          - py39-Flask
          - py39-Flask-HTTPAuth
          - py39-Flask-WTF
          - py39-markdown
          - py39-passlib
          - py39-sqlite3
          - sqlite3
        cached: true
      notify:
        - update supervisor

    - name: ensure web site root directory exists
      file:
        dest: "{{ vhosts_root }}/{{ domain_name }}/web"
        state: directory
        owner: keith
        group: www
        mode: "0755"

    - name: populate domains.txt
      lineinfile:
        dest: "{{ acme_client_root }}/domains.txt"
        create: true
        line: "{{ domain_name }} www.{{ domain_name }}"
      notify:
        - reload nginx
        - generate missing certificates

    - name: copy up custom vhost config
      template:
        src: "vhost.j2"
        dest: "{{ webserver_config_root }}/vhosts/{{ domain_name }}"
      notify:
        - reload nginx
        - generate missing certificates

    - name: copy up site
      synchronize:
        src: "{{ build_dir.path }}/"
        dest: "{{ vhosts_root }}/{{ domain_name }}/web"
        group: false
        owner: false
        perms: false
        delete: true

    - name: ensure app directory exists
      file:
        dest: "{{ vhosts_root }}/{{ domain_name }}/inklings"
        state: directory
        owner: keith
        group: www
        mode: "0755"

    - name: copy up komorebi
      synchronize:
        src: "komorebi/komorebi"
        dest: "{{ vhosts_root }}/{{ domain_name }}/inklings"
        group: false
        owner: false
        perms: false
        delete: true
      notify:
        - update supervisor

    - name: ensure database directory exists
      file:
        dest: "{{ db_path | dirname }}"
        state: directory
        owner: www
        group: www
        mode: "0755"

    - name: populate database with schema
      command: "sqlite3 {{ db_path }}"
      args:
        stdin: "{{ lookup('file', 'komorebi/schema/komorebi.sql') }}"
        creates: "{{ db_path }}"
      become: false

    - name: deploy supervisor configuration
      template:
        src: "komorebi.ini.j2"
        dest: "/usr/local/etc/supervisord.d/komorebi.ini"
      notify:
        - update supervisor

    - name: deploy site configuration
      template:
        src: "komorebi.cfg.j2"
        dest: "{{ vhosts_root }}/{{ domain_name }}/komorebi.cfg"
      notify:
        - update supervisor

    - name: ensure supervisor is aware of the app
      supervisorctl:
        name: komorebi
        state: present

  handlers:
    - name: generate missing certificates
      command:
        argv:
          - "{{ acme_client_root }}/acme-domain-renew"
          - "-c"
          - "{{ acme_client_root }}"
          - "-w"
          - "{{ acme_challenge_dir }}"
          - "-t"
          - "{{ tls_root }}"

    - name: reload nginx
      service:
        name: nginx
        state: reloaded

    - name: update supervisor
      supervisorctl:
        name: komorebi
        state: restarted
