---
site_name: talideon.com
copyright: Keith Gaughan, 2001-2020

theme:
  name: null
  custom_dir: ../themes/minimal

markdown_extensions:
  - smarty
  - sane_lists

plugins:
  - search

nav:
  - Home: index.md
